### ISSUE TITLE
combobox with Voiceover and safari OSX

### ISSUE THREAD

**Issue by goetsu** [accdc/tsg#1]
When I try the demo here with Voiceover on : 
https://github.com/accdc/tsg/blob/master/AccDC%20Technical%20Style%20Guide/Coding%20Arena/ARIA%20Comboboxes/ARIA%20Comboboxes%20%28Native%20Inputs%2C%20Editable%20with%20Substring%20Match%29/demo.htm

If i use the arrow keys to navigate in the list of suggestions it doesn't work at all. 
I can use alt+down arrow key to navigate down the list but when I use alt+up arrow key it move up it select the previous choice and close the list so no way to move up in the list

I'm on 10.10.3 with safari 8.0.6

**Comment by goetsu** [comment]
Ok this bug come from activation of quick navigation so now I can use up and down arrow key but the current value in the list isn't announced when I move focus in the list

**Comment by accdc** [comment]
Thanks, I've been going through the code, and this looks to be the result of VoiceOver not properly reflecting the aria-activedescendant attribute when it changes as part of the Combobox when the arrow keys are used to change values.

The Combobox widget is programmed according to the ARIA matrix at
http://whatsock.com/training/matrices/#combobox

Can you please do me a favor and submit this as a bug to Apple by sending a message to accessibility@apple.com
Including the OS and browser versions you are using, and a link to the page to reproduce the issue?

Simply specify this as a platform bug where VoiceOver is not properly announcing the value of a Combobox when aria-activedescendant is used to reference the selected Option node.

I've filed many such bugs with Apple against iOS in the past couple of years as well.

Thanks,
Bryan

**Comment by accdc** [comment]
This appears to now work correctly in OS X. Please file another bug with updated version details if you notice any remaining issues.
