### ISSUE TITLE
 Calendar - Navigable (2.4.7.aa) Visible Focus for selected date 

### ISSUE THREAD

**Issue by GovindaAgarwal** [accdc/tsg#10]
Hello @accdc 

Trust things are going great on your side. 

We have an issue where we are not able to see the focus state on selection of the date. When I select  date on the calendar focus carat line should be different. 

Steps to Replicate: Navigate to Calendar Next button and press TAB key.

Current behavior: Focus state is not visible on the selected Date.

Expected behavior: Focus carat line should be different from selected state.

Please let me know if you need additional details for this.

**Comment by GovindaAgarwal** [comment]
Hi @accdc 

Appreciate any update on this.

**Comment by accdc** [comment]
Hi,
Do you see the same issue on this page?
http://whatsock.com/tsg/Coding%20Arena/ARIA%20Date%20Pickers/ARIA%20Date%20Picker%20(Basic)/demo.htm

**Comment by GovindaAgarwal** [comment]
Hi @accdc 

Yes the issue persists in the link you provided. 

The selected date in the calendar should be different from focus state in some way.

**Comment by accdc** [comment]
This should now be fixed as well, since the focused element has a focus outline whereas the selected date does not.

td.selected {background: #E2A037;}

div.calendar *:focus, div.commentAdd *:focus {
    background: #E2A037;
        outline: blue 2px inset;
}

**Comment by GovindaAgarwal** [comment]
Hi @accdc 

I tested in the same URL- http://whatsock.com/tsg/Coding%20Arena/ARIA%20Date%20Pickers/ARIA%20Date%20Picker%20(Basic)/demo.htm and the issue seems to exists.

I don't see any difference in focus state between selected date and focused date. Both seems to have same focus carat outline.

**Comment by accdc** [comment]
@gericci Can you help with this? I'm having trouble diagnosing this without sight.

**Comment by GovindaAgarwal** [comment]
@accdc 

Sure, anything I can do to help diagnose this.

Can we change the background color for focus date to be same background color as the non focus state? The carat outline should be good enough to distinguish from the selected date focus provided the background color is not same as that of the selected date background.  

The selected date background color should stay #E2A037 even when user focuses out of the selected date using keyboard navigation in order to differentiate selected date vs focus date.

**Comment by accdc** [comment]
Hi, yes of course you can change the CSS however you like, it won't have any negative impact on screen reader or keyboard accessibility.

**Comment by LaurenceRLewis** [comment]
It looks like this is caused by the roving '.selected' class which sets the background colour. A possible solution is to add a new class ie. 'set' to the cell associated with the active date in the input field.  This can then be fixed until the active date is changed and then the class applied to the new active cell. The roving selected class can then be styled separately to indicate the element in focus.

Something like
td.selected:focus,
td.selected:hover {style as required moved with the focus}
td.set {background: #E2A037;}

A scripting change is required to add the additional 'set' class.

**Comment by GovindaAgarwal** [comment]
@accdc 

Thanks for the feedback. 

That sounds correct and will keep the styles / focus state different from selected date to active date user is hovering. I am trying to avoid any custom changes using your library and this is pretty much a calendar functionality for keyboard user. 

Let me know how you would like me to proceed.

**Comment by accdc** [comment]
Thanks for helping to diagnose, the problem I'm having is that I'm not understanding what is expected to happen visually when mousing versus arrowing.

So, currently the "selected" class changes as you arrow using the keyboard, but this does not do the same thing when simply hovering the mouse over the dates. So is the expected behavior to do the same thing when hovering the mouse over the dates?

E.G Is hovering over a date supposed to look the same as when arrowing between the dates?

**Comment by GovindaAgarwal** [comment]
@accdc 

No problems...my pleasure. 

It's not about hovering over Vs using arrows. Neither I am expecting the behavior to be same when hovering mouse over the dates vs using arrows. 

Let me try to explain here what is the requirement:

1. Go to the AccDc date picker and select a date and close the date picker. 
2. Now open the date picker again and the focus will now be on the selected date
3. Using arrows keys from your keyboard browse through the dates and the focus from the selected date is lost as the new dates are highlighted with same styles and carat line 
4.  Ideally the originally selected date should stay in the same focus state (color code and focus border) to indicate this was user previous selection and the new dates user is browsing using arrows should be focused in a different style e.g. color code and focus border. The goal is to differentiate user previously selected date vs the new dates is is browsing using keyboard or mouse or touch. 

Hope this clarifies.

**Comment by accdc** [comment]
Ah, that helps a lot, thanks. That does make sense, there is actually an ARIA attribute for this purpose too named aria-current which I've been intending to add for the same reason. I'll work on this next and see about the styling then too.

**Comment by GovindaAgarwal** [comment]
perfect ...thanks @accdc

**Comment by accdc** [comment]
Hi, I believe I corrected this in the latest push. Can you retest the live examples?

**Comment by GovindaAgarwal** [comment]
Hi @accdc 

This works perfect now, just one more change required. 

When user moves the focus from the new dates to previous and next buttons in the calendar then both the dates are  with same background color. 

Requesting for only 1 change - Can we remove the background color from active date user is browsing using left and right arrows key and keep only the focus outline? 

This should take care of the issue. Otherwise when the user focuses in months and years navigation arrows then it will show two dates with same color. 

Steps to reproduce:

- Open Calendar in mozilla or chrome browser
- Using right arrow key to navigate to 22nd Sep date
- Using tab key navigate to Next arrow key

You will be able to find below scenario. 

![two dates with same color](https://user-images.githubusercontent.com/5991115/30223533-43acc362-9499-11e7-8eec-4aa896a60320.png)

**Comment by GovindaAgarwal** [comment]
Hi @accdc 

Appreciate any update you can provide on above pending issue. Let me know if you have any questions regarding it.

**Comment by accdc** [comment]
Hi, sorry for the delay, I thought I had fixed this in the last release. I'll check again. So to be clear, I should remove the background color on the focused element but maintain this on the current date, and use only focus outline to indicate the focused date when moving focus?

**Comment by GovindaAgarwal** [comment]
Hi @accdc 

Thanks for the response. 

Yes, what you stated is precisely correct. Please let me know when the fix is applied.

**Comment by accdc** [comment]
Hi, this should now be fixed, all repos have been updated. Please let me know if this does the trick.

**Comment by GovindaAgarwal** [comment]
Hi @accdc 

Seems like all the issues were fixed in different version of the calendar e.g. http://whatsock.com/tsg/Coding%20Arena/ARIA%20Date%20Pickers/ARIA%20Date%20Picker%20(Basic)/demo.htm 

And we are using this version of the calendar - http://whatsock.com/tsg/Coding%20Arena/ARIA%20Date%20Pickers/ARIA%20Date%20Picker%20(with%20Disabled%20Date%20Ranges)/demo.htm

Are both versions similar? I thought I raised this query in the same project and did not realize there were two versions of the calendar. 

Appreciate your help!

**Comment by accdc** [comment]
Hi, if you pull in the latest repo archive, you will see that the Calendar Module is now version 1.22, so this should be compared with the version you are currently using to make sure you have the latest code. To see what the focus styling is within these examples, view the file named calendar.css within each of the 'css' folders within each example by searching for ":focus" to see how the styling is applied. Please feel free to change these however you like if you want differint styling though.

**Comment by GovindaAgarwal** [comment]
@accdc 

thanks for the clarification. 

We are already updating the styles as per our requirements.
