### ISSUE TITLE
Calendar - Adaptable(1.3.2.a) Meaningful Sequence - close button

### ISSUE THREAD

**Issue by GovindaAgarwal** [accdc/tsg#11]
Hi @accdc 

Could you please provide any recommendation on the issue below?

Steps to Replicate: Navigate to Calendar and press TAB key.

Current behavior: User don’t have any option to move out of the calendar.

Expected behavior: Focus is trapped inside the modal, hence user should have option to close the calendar modal.

Suggestion: We can have 2 options.

Option1: Visible information about "user can close the calendar modal by pressing Esc key" before calender content by way of tooltip or visible text.

Option2: Provide close button.

**Comment by GovindaAgarwal** [comment]
Hi @accdc 

We have taken care of this and hence marking this as resolved.

**Comment by accdc** [comment]
Hi, apologies for the delay, I've been swamped with other projects of late. 

All of the AccDC Datepicker constructs are programmed to close when Escape is pressed after the datepicker opens. Was this not working on your end?
