### ISSUE TITLE
Calendar - Adaptable(1.3.2.a) Meaningful Sequence - lost focus

### ISSUE THREAD

**Issue by GovindaAgarwal** [accdc/tsg#12]
Hi @accdc 

Focus is getting lost when user is clicking on next or previous button / arrows on the calendar and the focus comes to date on the calendar.  

Steps to Replicate: Navigate to Calendar Next/Previous button using TAB key and press enter.

Current behavior: Focus is getting lost when user is clicking on Next/Previous button.

Expected behavior: Focus should remain on the same button (Next/Previous) button.

Appreciate if you could look into this.

**Comment by GovindaAgarwal** [comment]
Hi @accdc 

Appreciate any update on this.

**Comment by accdc** [comment]
Hi, this was intentional when I built it, otherwise a blind person would not know which month was being activated, since the intent is to use PageUp and PageDown to navigate by month while focus is within the calendar.


I can add this functionality, but I won't be able to look into it until next week at the earliest.

**Comment by GovindaAgarwal** [comment]
Hi @accdc 

Thanks for the feedback. However if the user wants to continue clicking on the next months, then he would not know how to come back to month for navigation. 

Appreciate if you could let me know when this functionality is added.

**Comment by accdc** [comment]
I've already started looking into it, should be done by next week. I'll update this issue when it's complete.

**Comment by accdc** [comment]
Hi,
This has been fixed and is live in all of the repos where this module is present.

Test url: http://whatsock.com/tsg/Coding%20Arena/ARIA%20Date%20Pickers/ARIA%20Date%20Picker%20(Basic)/demo.htm

**Comment by GovindaAgarwal** [comment]
Thanks @accdc 

This is fixed and working fine.
