### ISSUE TITLE
selected date and focused date issue

### ISSUE THREAD

**Issue by dominicdsouza1991** [accdc/tsg#13]
When navigating with the keyboard the current selected date changes. This is not that evident at first and is evident only  when we  from the last day of a month to the next month using the arrow keys.

This is because  dc.fn.current and dc.range.current both point to the same object. during assignment
`dc.fn.current =  dc.range.current`

which should be something like 

`dc.fn.current = jQuery.extend(true, {}, dc.range.current); // Deep cloning the object`
This has solved the issue.

**Comment by accdc** [comment]
Hi, that is strange, thanks for the help! I'll queue this up to be fixed soon and post an update here when it's uploaded.

**Comment by accdc** [comment]
My apologies, I accidentally replied to a different issue here by mistake.

I just corrected the issue, but used $A.internal.extend instead, which does the same thing but normalizes equally across jQuery, Dojo, and MooTools so the same code will work within all of these.

Please retest the latest archive code and reopen this if you notice any remaining issues, hopefully this one is working properly now though.

**Comment by accdc** [comment]
Closing this for now to clear the queue since the issue appears to be fixed.
