### ISSUE TITLE
Datepicker auto open not saving date.

### ISSUE THREAD

**Issue by heatworld1** [accdc/tsg#24]
Hello,

In the ARIA Date Pkcer(Basic, Auto Open) when clicking on the input the calendar opens.
Then when I select a date it does not update the input. It only updates when you click the calendar button to bring up the calendar and then selecting a date.

Also with the auto-open setting on. If you click the calendar button and select a date it will update the input. But then your settings for the input don't apply anymore.

**Comment by accdc** [comment]
Hi,
Thank you for your patience, I believe I have fixed this issue. I've updated all the live pages plus the GitHub repos, so if you could please retest this to verify it works as expected, I'd greatly appreciate it.

Thank you as well for bringing this to my attention. It's a very difficult bug for a blind person like myself to catch.

**Comment by heatworld1** [comment]
Hello, I do see that the input is updated when you open the calendar and select a date. What was the fix, I don't see the merge commit?

The other issue though is still apparent.

Steps to reproduce:
1.  [http://whatsock.com/tsg/Coding%20Arena/ARIA%20Date%20Pickers/ARIA%20Date%20Picker%20(Basic,%20ReadOnly%20Auto%20Open%20plus%20Disabled%20Ranges)/demo.htm](url)
2. Click the calendar button.
3. Close calendar
4. Click input to have the calendar open <-- nothing happens

**Comment by accdc** [comment]
Hi,
The fix for clicking and saving was to add a "mouseWithin" flag within the blur handler to prevent premature closing.

I just pushed the fix for the focus issue, which should correct the second issue you reported.

Does this do the trick?

**Comment by heatworld1** [comment]
Oh OK
So I'm trying it again and I get the same kind of error.

1.http://whatsock.com/tsg/Coding%20Arena/ARIA%20Date%20Pickers/ARIA%20Date%20Picker%20(Basic,%20ReadOnly%20Auto%20Open%20plus%20Disabled%20Ranges)/demo.htm
2. Click the input, this opens the calendar.
3. Select a date, this then closes the calendar.
4. Click on the input again to change what you just choose <-- nothing happens

**Comment by accdc** [comment]
Thanks, I fixed the one where you click the expand button, then close the calendar, then click the edit field.

I just pushed another update that fixes when you click the edit field, click a date in the calendar or close it without picking a date, then click the edit field once again to reopen the calendar.

Does this do the trick?

**Comment by heatworld1** [comment]
Thank you for that fix as well.
The thing is it seems as though when the setting for clicking on the input to open the calendar is set then the settings for opening the calendar via the button don't work right together.

[Link to site](http://whatsock.com/tsg/Coding%20Arena/ARIA%20Date%20Pickers/ARIA%20Date%20Picker%20(Basic,%20ReadOnly%20Auto%20Open%20plus%20Disabled%20Ranges)/demo.htm)

solved:
- On click of input the calendar opens and when you click on the date is updated.
- When constantly opening the calendar via input it opens the calendar and updates.

issues:
- Open calendar when clicking on the input select date. Then press the calendar button and then select a date. If you then click the input again the calendar does not open.
- Click the calendar to open the calendar and select the date. Then click the input, the calendar doesn't open.

I still thank you for taking the time for the other fixes.

**Comment by accdc** [comment]
That's no problem, I would rather know about any issues than not, so I appreciate your feedback.

I think this time it's fixed. I tried all of the combos that you mentioned, and basically every time you click the input field, it resets the initial flags as though every time is the first time. This way it won't matter if you click the button or the edit field first, save a date, then click the field again, because the act of clicking will reset it regardless.

All the pages have been uploaded and pushed, so please let me know if that works as you expect.

**Comment by heatworld1** [comment]
I just tested it and it works like a charm!
Thank you for looking and fixing this.
