### ISSUE TITLE
Suggest adding a section on aria-disabled to the ARIA Warnings section

### ISSUE THREAD

**Issue by OwenEdwards** [accdc/tsg#6]
Section should highlight that:
- If a `<button>` element is `disabled`, it is removed from the tab order; an element with `role="button"` and `aria-disabled="true"` is not automatically removed from the tab order (its tabIndex needs to be changed programmatically to achieve this).
- If a `<button>` element is `disabled`, it does not generate click events when clicked with the mouse or if a screen reader user moves the Virtual Cursor to it and activates it. On an element with `role="button"` and `aria-disabled="true"`, click events are still fired and the JavaScript handling of keyboard events will still operate unless disabled programmatically.

Similar issues probably occur with the use other of roles instead of native elements.

**Comment by accdc** [comment]
Added this within the Improper Use of ARIA section
