### ISSUE TITLE
combobox  - making selection from dropdown values

### ISSUE THREAD

**Issue by GovindaAgarwal** [accdc/tsg#8]
using the jaws screen reader encountered following issue:

When trying to navigate the drop down values and the last value is encountered, 

the selected option does not go to the first option in the dropdown on pressing down arrow and it keeps reading blank

Ideally it should loop through the values in the dropdown from the top when the last value is reached.

**Comment by accdc** [comment]
Hi, thanks for the feedback.

I'll add loop traversal as a feature request for the near future.

I was not able to reproduce the announcement of "blank", I tested this using IE11, Firefox, and Chrome on Windows7 using JAWS18.

Which operating system, browser, and version of JAWS are you using?

Thanks,
Bryan

**Comment by accdc** [comment]
Hi,
The ARIA Combobox module has been updated to support automatic looping forward and backward when arrowing as expected. Thanks again for the issue to let me know about this.
All the best,
Bryan

**Comment by GovindaAgarwal** [comment]
Thanks Bryan. 

Appreciate it. Will check and get back to you. 

Meanwhile could you please share the link for updated combobox module or is it the same?

**Comment by accdc** [comment]
No problem, all of the same links should now work with the update.

**Comment by GovindaAgarwal** [comment]
Bryan,

Sorry for delayed response on this.

Yes this has fixed the issue. 

Thanks for helping out with this.
